import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Página inicial</h1>
      <Link href={"/new-post"}>Nova postagem</Link>
      <Link href={"/post/1"}>Post 1</Link>
    </>
  );
}
